version: "3"
services:
  php-apache:
    build: .
    ports:
     - "8080:80"
    links:
     - dbmysql 
    volumes:
     - ./app:/var/www/html

  dbmysql:
    image: mysql:5
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: teste
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"